Improve error for non existent default
If keystone default type did not exist in the DB we would get the
generic volume type not found error:

  ERROR: Volume type with name FAULTY could not be found. (HTTP 404)

Which was confusing because we didn't set any volume type in our call.

With this patch we'll be returning a specific error message that should
help us clearly identify the issue:

  ERROR: Default Volume type FAULTY for project could not be found.
  (HTTP 404)

  ERROR: Default Volume type FAULTY for user could not be found.  (HTTP
  404)